### ISSUE TITLE
Simplify creating new Transaction process

### ISSUE THREAD

**Issue by josefwijaya** [gallactic/intergallactic#13]
**Current way**
The current way of creating new transaction:
- Send Transaction
```
const txn = {
  from: [{
    address: 'acFVrNat8Y8Evid4fcJzN5KxyEAyuHS6Tuu',
    amount: 10
  }],
  to: [{
    address: 'acWmVcNrHzxBF8L25vdiKLsz664ZGkYmPRj',
    amount: 10
  }]
};
const option = {
  type: 1,
  unit: 'boson'
};
const newTxn = new igc.Transaction(txn, option);
newTxn.signNBroadcast(privKey)
  .then(res => {
  
  })

/* OR */

const newTxn = new igc.Transaction(txn, option);
newTxn.sign(privKey)
  .then(signature => {
    const signatories = [{
      signature, publicKey: pubKey
    }]
    return newTxn.call(signatories);
  })
  .then(res => {
  
  });
```
- Call Transaction
```
const txn = {
  from: {
    address: 'acFVrNat8Y8Evid4fcJzN5KxyEAyuHS6Tuu',
    amount: 10
  },
  to: {
    address: '',
    amount: 10
  },
  gasLimit: 1,
  data: '010203' // currently require an input of byte array
}
const option = {
  type: 1,
  unit: 'boson'
};
const newTxn = new igc.Transaction(txn, option);
newTxn.signNBroadcast(privKey)
  .then(res => {
  
  })

/* OR */

const newTxn = new igc.Transaction(data.txn, { type: data.txnType });
newTxn.sign(data.privKey)
  .then(signature => {
    const signatories = [{
      signature, publicKey: data.pubKey
    }]
    return newTxn.call(signatories);
  })
  .then(res);
```

**New way** (suggestion)
A suggestion of more simple way of creating transaction
- Send Transaction
```
const tx = new Transaction({
  to: 'bbb',
  amount: 10
  fee: 1
});

tx.send(pk)
  .then(res => {

  })

/* OR */

tx.type = 'SendTx';

tx.sign(pk)
  .then(() => {
    tx.broadcast()
  })

```
- Call Transaction
```
const tx = new Transaction({
  to: 'bbb',
  amount: 10
  gasLimit: 1,
  data: '010203'
})

tx.call(pk)
  .then(res => {

  })

/* OR */

tx.type = 'CallTx';

tx.sign(pk)
  .then(() => {
    tx.broadcast()
  })
```

The concept will similarly applied to Bond, Unbond and Permission Transaction as well.

**Comment by b00f** [comment]
@josefwijaya as I can see you are going to simplify the transaction. I have a suggestion, We can try to make our PAI closer to Ethereum since it's well known by developers. look here: https://web3js.readthedocs.io/en/1.0/web3-eth.html#sendtransaction

Also you can check here maybe you can get some ideas: 
https://www.blockcypher.com/dev/ethereum/?javascript#creating-transactions

**Comment by josefwijaya** [comment]
@b00f I believe, your suggestion is more towards different programming style. In Web3, they are more towards functional programming. In Intergallactic, we are more towards object oriented in this case. I think it's best to keep current approach as object oriented in this case.

But yeah, let's hear others opinion as well

**Comment by b00f** [comment]
@josefwijaya We can beat them!

**Comment by josefwijaya** [comment]
#14
