### ISSUE TITLE
current Signing Transaction process might be vulnerable to security threat

### ISSUE THREAD

**Issue by josefwijaya** [gallactic/intergallactic#5]
Upon signing the transaction, the private key here is exposed in plain text format.

**Comment by b00f** [comment]
We should avoid saving or holding private key in plain format.

**Comment by josefwijaya** [comment]
After further discussion yesterday, the highlight is that intergallactic require private key to be in plain text format to sign transaction. So the keystore feature implementation (unlocking keystore to gain access to plain private key) would be done separately

**Comment by b00f** [comment]
Please make sure users can also use intergalalctic if they want to use plain private_key. However we should provide safer methods for interacting with the blockchain...
